global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "docker"
    static_configs:
      - targets: ["host.docker.internal:9090"]
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-db:9187"]
  - job_name: "redis"
    static_configs:
      - targets: ["redis-cache:6379"] 
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']


